# Generated by CodiumAI
from src.algebra import correlation_matrix

class TestCorrelationMatrix:

    # Computes correlation matrix for a DataFrame with only numeric columns
    def test_numeric_columns_only(self):
        import pandas as pd
        from pandas.testing import assert_frame_equal

        data = {
            'A': [1, 2, 3, 4],
            'B': [4, 3, 2, 1],
            'C': [1, 2, 3, 4]
        }
        df = pd.DataFrame(data)
        expected_corr = df.corr()

        result = correlation_matrix(df)

        assert_frame_equal(result, expected_corr)

    # DataFrame with no numeric columns
    def test_no_numeric_columns(self):
        import pandas as pd

        data = {
            'A': ['a', 'b', 'c', 'd'],
            'B': ['w', 'x', 'y', 'z']
        }
        df = pd.DataFrame(data)
        expected_corr = pd.DataFrame()

        result = correlation_matrix(df)

        assert result.equals(expected_corr)
